- removed boostbuild - re-adapted PKG_COPYSRC into configmake and make only - created pkg/Cairo eco-system

diff --git a/bbxb b/bbxb
--- a/bbxb
+++ b/bbxb
@@ -69,7 +69,7 @@ source "${BB_HOME}/data.functions"
 
 trap 'STATUS=${?}; \
 	echo >&2; \
-	echo "[${FUNCNAME[*]} - ERR: ${STATUS}]" >&2; \
+	echo "${ERROR_MSG:-ERR received.} [${FUNCNAME[*]} - ERR: ${STATUS}]" >&2; \
 	echo >&2; \
 	set +E +o pipefail; \
 	trap - SIGINT; \
